default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RAILS_DATABASE_HOST") { 'localhost' } %>
  timeout: 5000

development:
  <<: *default
  database: recordit_development

production:
  <<: *default
  database: recordit_production
